<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Project;
use Carbon\Carbon;
use Illuminate\Support\Facades\DB; // Importer le facade DB

class ProjectSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        // Désactiver les vérifications des clés étrangères pour éviter les problèmes d'ordre d'insertion
        DB::statement('SET FOREIGN_KEY_CHECKS=0;');

        // Insérer les projets parents (sans project_id)
        $parentProjects = [
            [
                'id' => 49,
                'title' => 'Programme d\'Éducation et de Formation',
                'description' => 'Fournir des opportunités d\'éducation et de formation professionnelle pour les jeunes et les adultes afin de leur permettre d\'acquérir des compétences et d\'améliorer leur employabilité.',
                'image' => null,
                'attachments' => null,
                'members' => null,
                'beneficiaries' => 'Jeunes et adultes',
                'order' => null,
                'status' => null,
                'intervention_zone' => 'Cotonou, Calavi, Bohicon',
                'start_date' => '2024-08-28',
                'end_date' => '2024-11-29',
                'user_id' => 1,
                'project_id' => null,
                'type' => 'programme',
                'strategic_axe_id' => 1,
                'department' => null,
                'village' => null,
                'district' => null,
                'result_id' => 1,
                'lessons_learned' => null,
                'created_at' => Carbon::create(2024, 9, 19, 11, 4, 47),
                'updated_at' => Carbon::create(2024, 9, 19, 11, 4, 47),
            ],
            [
                'id' => 50,
                'title' => 'Initiative pour l\'Autonomisation des Femmes',
                'description' => 'Offrir des formations en entrepreneuriat et en gestion financière aux femmes pour les aider à créer et gérer leurs propres entreprises.',
                'image' => null,
                'attachments' => null,
                'members' => null,
                'beneficiaries' => 'Femmes',
                'order' => null,
                'status' => null,
                'intervention_zone' => 'Cotonou, Calavi, Bohicon',
                'start_date' => '2024-07-14',
                'end_date' => '2024-12-19',
                'user_id' => 1,
                'project_id' => null,
                'type' => 'programme',
                'strategic_axe_id' => 2,
                'department' => null,
                'village' => null,
                'district' => null,
                'result_id' => 2,
                'lessons_learned' => null,
                'created_at' => Carbon::create(2024, 9, 19, 11, 4, 47),
                'updated_at' => Carbon::create(2024, 9, 19, 11, 4, 47),
            ],
            [
                'id' => 51,
                'title' => 'Accès à la Santé de Base',
                'description' => 'Mettre en place des cliniques mobiles et des programmes de sensibilisation pour améliorer l\'accès aux soins de santé de base dans les communautés défavorisées.',
                'image' => null,
                'attachments' => null,
                'members' => null,
                'beneficiaries' => 'Communautés défavorisées',
                'order' => null,
                'status' => null,
                'intervention_zone' => 'Cotonou, Calavi, Bohicon',
                'start_date' => '2024-09-01',
                'end_date' => '2025-01-17',
                'user_id' => 1,
                'project_id' => null,
                'type' => 'programme',
                'strategic_axe_id' => 1,
                'department' => null,
                'village' => null,
                'district' => null,
                'result_id' => 1,
                'lessons_learned' => null,
                'created_at' => Carbon::create(2024, 9, 19, 11, 4, 47),
                'updated_at' => Carbon::create(2024, 9, 19, 11, 4, 47),
            ],
            [
                'id' => 52,
                'title' => 'Programme de Microcrédit',
                'description' => 'Accorder des prêts à faible intérêt pour aider les petits entrepreneurs et les familles à démarrer ou développer leurs activités économiques.',
                'image' => null,
                'attachments' => null,
                'members' => null,
                'beneficiaries' => 'Petits entrepreneurs et familles',
                'order' => null,
                'status' => null,
                'intervention_zone' => 'Cotonou, Calavi, Bohicon',
                'start_date' => '2024-06-03',
                'end_date' => '2024-12-28',
                'user_id' => 1,
                'project_id' => null,
                'type' => 'programme',
                'strategic_axe_id' => 1,
                'department' => null,
                'village' => null,
                'district' => null,
                'result_id' => 1,
                'lessons_learned' => null,
                'created_at' => Carbon::create(2024, 9, 19, 11, 4, 47),
                'updated_at' => Carbon::create(2024, 9, 19, 11, 4, 47),
            ],
            [
                'id' => 53,
                'title' => 'Sécurité Alimentaire',
                'description' => 'Mettre en œuvre des projets de jardins communautaires et de banques alimentaires pour garantir un accès régulier à une alimentation suffisante et nutritive.',
                'image' => null,
                'attachments' => null,
                'members' => null,
                'beneficiaries' => 'Familles en situation de précarité alimentaire',
                'order' => null,
                'status' => null,
                'intervention_zone' => 'Cotonou, Calavi, Bohicon',
                'start_date' => '2024-09-02',
                'end_date' => '2024-12-13',
                'user_id' => 1,
                'project_id' => null,
                'type' => 'programme',
                'strategic_axe_id' => 1,
                'department' => null,
                'village' => null,
                'district' => null,
                'result_id' => 1,
                'lessons_learned' => null,
                'created_at' => Carbon::create(2024, 9, 19, 11, 4, 47),
                'updated_at' => Carbon::create(2024, 9, 19, 11, 4, 47),
            ],
            [
                'id' => 54,
                'title' => 'Programme de Logement Abordable',
                'description' => 'Développer des projets de logement abordable pour les familles à faible revenu afin d\'améliorer leurs conditions de vie.',
                'image' => null,
                'attachments' => null,
                'members' => null,
                'beneficiaries' => 'Familles à faible revenu',
                'order' => null,
                'status' => null,
                'intervention_zone' => 'Cotonou, Calavi, Bohicon',
                'start_date' => '2024-06-03',
                'end_date' => '2024-09-26',
                'user_id' => 1,
                'project_id' => null,
                'type' => 'programme',
                'strategic_axe_id' => 1,
                'department' => null,
                'village' => null,
                'district' => null,
                'result_id' => 1,
                'lessons_learned' => null,
                'created_at' => Carbon::create(2024, 9, 19, 11, 4, 47),
                'updated_at' => Carbon::create(2024, 9, 19, 11, 4, 47),
            ],
            [
                'id' => 55,
                'title' => 'Protection des Enfants et des Adolescents',
                'description' => 'Mettre en place des programmes de protection pour prévenir les abus, l\'exploitation et la négligence des enfants et des adolescents.',
                'image' => null,
                'attachments' => null,
                'members' => null,
                'beneficiaries' => 'Enfants et adolescents',
                'order' => null,
                'status' => null,
                'intervention_zone' => 'Cotonou, Calavi, Bohicon',
                'start_date' => '2024-08-04',
                'end_date' => '2024-09-01',
                'user_id' => 1,
                'project_id' => null,
                'type' => 'programme',
                'strategic_axe_id' => 3,
                'department' => null,
                'village' => null,
                'district' => null,
                'result_id' => 3,
                'lessons_learned' => null,
                'created_at' => Carbon::create(2024, 9, 19, 11, 4, 47),
                'updated_at' => Carbon::create(2024, 9, 19, 11, 4, 47),
            ],
            [
                'id' => 56,
                'title' => 'Programme de Formation en Santé Mentale',
                'description' => 'Offrir des formations et des services de soutien en santé mentale pour aider les individus à gérer le stress et les défis psychologiques liés à la pauvreté.',
                'image' => null,
                'attachments' => null,
                'members' => null,
                'beneficiaries' => 'Individus affectés par le stress et les défis psychologiques',
                'order' => null,
                'status' => null,
                'intervention_zone' => 'Cotonou, Calavi, Bohicon',
                'start_date' => '2024-09-04',
                'end_date' => '2024-09-19',
                'user_id' => 1,
                'project_id' => null,
                'type' => 'programme',
                'strategic_axe_id' => 3,
                'department' => null,
                'village' => null,
                'district' => null,
                'result_id' => 3,
                'lessons_learned' => null,
                'created_at' => Carbon::create(2024, 9, 19, 11, 4, 47),
                'updated_at' => Carbon::create(2024, 9, 19, 11, 4, 47),
            ],
            [
                'id' => 65,
                'title' => 'Création d\'école',
                'description' => 'Je vous suis encore et toujours',
                'image' => null,
                'attachments' => null,
                'members' => null,
                'beneficiaries' => 'Jeunes, Enfants',
                'order' => null,
                'status' => null,
                'intervention_zone' => 'Cotonou',
                'start_date' => null,
                'end_date' => null,
                'user_id' => 1,
                'project_id' => null,
                'type' => 'projet',
                'strategic_axe_id' => null,
                'department' => null,
                'village' => null,
                'district' => null,
                'result_id' => null,
                'lessons_learned' => null,
                'created_at' => Carbon::create(2024, 9, 19, 11, 4, 47),
                'updated_at' => Carbon::create(2024, 9, 19, 11, 4, 47),
            ],
        ];

        foreach ($parentProjects as $project) {
            Project::updateOrCreate(['id' => $project['id']], $project);
        }

        // Insérer les projets enfants (avec project_id)
        $childProjects = [
            [
                'id' => 57,
                'title' => 'Atelier de Formation en Compétences Numériques',
                'description' => 'Formation gratuite en compétences numériques pour les jeunes afin d\'améliorer leur employabilité dans le secteur technologique.',
                'image' => null,
                'attachments' => null,
                'members' => null,
                'beneficiaries' => 'Jeunes',
                'order' => null,
                'status' => 'en_cours',
                'intervention_zone' => 'Cotonou, Calavi',
                'start_date' => '2024-09-30',
                'end_date' => '2024-09-30',
                'user_id' => 1,
                'project_id' => 54, // Référence au projet 54
                'type' => 'projet',
                'strategic_axe_id' => 2,
                'department' => null,
                'village' => null,
                'district' => null,
                'result_id' => 2,
                'lessons_learned' => null,
                'created_at' => Carbon::create(2024, 9, 30, 7, 50, 23),
                'updated_at' => Carbon::create(2024, 9, 30, 7, 50, 23),
            ],
            [
                'id' => 58,
                'title' => 'Formation en Entrepreneuriat pour Femmes',
                'description' => 'Programme de formation en entrepreneuriat pour aider les femmes à lancer et gérer leurs propres entreprises.',
                'image' => null,
                'attachments' => null,
                'members' => null,
                'beneficiaries' => 'Femmes',
                'order' => null,
                'status' => 'en_cours',
                'intervention_zone' => 'Bohicon, Calavi',
                'start_date' => '2024-09-17',
                'end_date' => '2025-09-17',
                'user_id' => 1,
                'project_id' => 54, // Référence au projet 54
                'type' => 'projet',
                'strategic_axe_id' => 1,
                'department' => null,
                'village' => null,
                'district' => null,
                'result_id' => 1,
                'lessons_learned' => null,
                'created_at' => null, // Laisser à null si vous ne souhaitez pas spécifier
                'updated_at' => null, // Laisser à null si vous ne souhaitez pas spécifier
            ],
            [
                'id' => 59,
                'title' => 'Clinique Mobile de Santé',
                'description' => 'Installation de cliniques mobiles pour fournir des soins de santé de base dans les zones rurales et défavorisées.',
                'image' => null,
                'attachments' => null,
                'members' => null,
                'beneficiaries' => 'Communautés défavorisées',
                'order' => null,
                'status' => 'en_cours',
                'intervention_zone' => 'Cotonou, Bohicon',
                'start_date' => '2024-09-17',
                'end_date' => '2025-06-17',
                'user_id' => 1,
                'project_id' => 51, // Référence au projet 51
                'type' => 'projet',
                'strategic_axe_id' => 1,
                'department' => null,
                'village' => null,
                'district' => null,
                'result_id' => 1,
                'lessons_learned' => null,
                'created_at' => null, // Laisser à null si vous ne souhaitez pas spécifier
                'updated_at' => null, // Laisser à null si vous ne souhaitez pas spécifier
            ],
            [
                'id' => 60,
                'title' => 'Microcrédit pour Petits Entrepreneurs',
                'description' => 'Programme de microcrédit offrant des prêts à faible intérêt pour aider les petits entrepreneurs à développer leurs activités.',
                'image' => null,
                'attachments' => null,
                'members' => null,
                'beneficiaries' => 'Petits entrepreneurs',
                'order' => null,
                'status' => 'en_cours',
                'intervention_zone' => 'Calavi, Cotonou',
                'start_date' => '2024-10-19',
                'end_date' => '2024-10-26',
                'user_id' => 1,
                'project_id' => 55, // Référence au projet 55
                'type' => 'projet',
                'strategic_axe_id' => 2,
                'department' => null,
                'village' => null,
                'district' => null,
                'result_id' => 2,
                'lessons_learned' => null,
                'created_at' => Carbon::create(2024, 10, 9, 10, 1, 4),
                'updated_at' => null, // Laisser à null si vous ne souhaitez pas spécifier
            ],
            [
                'id' => 61,
                'title' => 'Jardins Communautaires pour la Sécurité Alimentaire',
                'description' => 'Création de jardins communautaires pour assurer un accès régulier à des aliments nutritifs dans les quartiers défavorisés.',
                'image' => null,
                'attachments' => null,
                'members' => null,
                'beneficiaries' => 'Familles en situation de précarité alimentaire',
                'order' => null,
                'status' => 'en_cours',
                'intervention_zone' => 'Bohicon, Calavi',
                'start_date' => '2024-09-17',
                'end_date' => '2025-05-17',
                'user_id' => 1,
                'project_id' => 49, // Référence au projet 49
                'type' => 'projet',
                'strategic_axe_id' => 1,
                'department' => null,
                'village' => null,
                'district' => null,
                'result_id' => 1,
                'lessons_learned' => null,
                'created_at' => null, // Laisser à null si vous ne souhaitez pas spécifier
                'updated_at' => null, // Laisser à null si vous ne souhaitez pas spécifier
            ],
            [
                'id' => 62,
                'title' => 'Construction de Logements Abordables',
                'description' => 'Construction de logements abordables pour les familles à faible revenu afin d\'améliorer leurs conditions de vie.',
                'image' => null,
                'attachments' => null,
                'members' => null,
                'beneficiaries' => 'Familles à faible revenu',
                'order' => null,
                'status' => 'en_cours',
                'intervention_zone' => 'Cotonou',
                'start_date' => '2024-09-17',
                'end_date' => '2026-09-17',
                'user_id' => 1,
                'project_id' => 52, // Référence au projet 52
                'type' => 'projet',
                'strategic_axe_id' => 1,
                'department' => null,
                'village' => null,
                'district' => null,
                'result_id' => 1,
                'lessons_learned' => null,
                'created_at' => null, // Laisser à null si vous ne souhaitez pas spécifier
                'updated_at' => null, // Laisser à null si vous ne souhaitez pas spécifier
            ],
            [
                'id' => 63,
                'title' => 'Programme de Protection des Enfants',
                'description' => 'Mise en place de services de soutien pour prévenir les abus et l\'exploitation des enfants et des adolescents.',
                'image' => null,
                'attachments' => null,
                'members' => null,
                'beneficiaries' => 'Enfants et adolescents',
                'order' => null,
                'status' => 'en_cours',
                'intervention_zone' => 'Cotonou, Calavi',
                'start_date' => '2024-09-27',
                'end_date' => '2024-10-06',
                'user_id' => 1,
                'project_id' => 52, // Référence au projet 52
                'type' => 'projet',
                'strategic_axe_id' => 1,
                'department' => null,
                'village' => null,
                'district' => null,
                'result_id' => 1,
                'lessons_learned' => null,
                'created_at' => Carbon::create(2024, 9, 20, 6, 36, 30),
                'updated_at' => null, // Laisser à null si vous ne souhaitez pas spécifier
            ],
            [
                'id' => 64,
                'title' => 'Ateliers de Santé Mentale',
                'description' => 'Organisation d\'ateliers et de sessions de soutien en santé mentale pour aider les individus à gérer le stress et les défis psychologiques.',
                'image' => null,
                'attachments' => null,
                'members' => null,
                'beneficiaries' => 'Individus affectés par le stress',
                'order' => null,
                'status' => 'en_cours',
                'intervention_zone' => 'Cotonou, Calavi',
                'start_date' => '2024-10-20',
                'end_date' => '2024-10-26',
                'user_id' => 1,
                'project_id' => 55, // Référence au projet 55
                'type' => 'projet',
                'strategic_axe_id' => 1,
                'department' => null,
                'village' => null,
                'district' => null,
                'result_id' => 1,
                'lessons_learned' => null,
                'created_at' => Carbon::create(2024, 10, 9, 11, 1, 27),
                'updated_at' => null, // Laisser à null si vous ne souhaitez pas spécifier
            ],
        ];

        foreach ($childProjects as $project) {
            Project::updateOrCreate(['id' => $project['id']], $project);
        }

        // Réactiver les vérifications des clés étrangères
        DB::statement('SET FOREIGN_KEY_CHECKS=1;');
    }
}
